### ISSUE TITLE
Add Godot API to translations?

### ISSUE THREAD

**Issue by JiRuifanCR** [godotengine/godot-docs-l10n#4] opened 2020-02-12 10:59 UTC
I sincerely apologize if this shouldn't be here, I've posted this at multiple places and there doesn't seem to be an answer(maybe I overlooked something). 
I am a docs translator and the Godot API(the final chapter of the docs) doesn't seem to be open for translation and therefore aren't present in any of the translated docs. As a result, all the :ref:`class_names`  to the Godot API are broken. Is it possible to add the Godot API chapter to the Weblate translations? Or maybe I am doing something wrong?

**Comment by qarlosh** [comment] 2020-02-12 11:24
The class reference (Godot API docs) are contributed in a different way than the rest of the docs. Here you have more information:
https://docs.godotengine.org/en/latest/community/contributing/ways_to_contribute.html#contributing-to-the-documentation

**Comment by akien-mga** [comment] 2020-02-12 11:27
Duplicate of godotengine/godot-docs#3162.

**Closed by akien-mga** 2020-02-12 11:27 UTC
