### ISSUE TITLE
Code blocks in documentation might as well be made translatable

### ISSUE THREAD

**Issue by User670** [godotengine/godot-docs-l10n#22] opened 2023-09-16 03:27 UTC
```python
# while code shouldn't be translated, comments might benefit from translations.
print("as well as some strings.")
```

**Comment by akien-mga** [comment] 2023-11-02 10:44
Duplicate of https://github.com/godotengine/godot-docs/issues/3284

**Closed as completed by akien-mga** 2023-11-02 10:44 UTC
Labels: duplicate
